### ISSUE TITLE
File FastGyroidInfill.py

### ISSUE THREAD

**Issue by jjrricardo** [sdavis175/SuperSlicer_Profiles#1]
Hello, I have a VORON 350x350, I was looking at your CFG files, congratulations, I was creating one based on several cfg found, I liked the organization and detail, I will download your .CFG files and adjust it to my printer
I downloaded your SuperSlicer config, you are using version 2.4 with post_process you can make the .py files available - post_process = "C:\\Python310\\python.exe \"C:\\Users\\ruuna\\Documents\ \3D Prints\\Programs\\FastGyroidInfill.py\""

**Comment by sdavis175** [comment]
It's been added to the root directory.
